# Generated by Django 6.0.7 on 2026-07-24 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiVien',
            fields=[
                ('ma_hv', models.CharField(db_column='MaHV', max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(db_column='HoTen', max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], db_column='GioiTinh', max_length=5)),
                ('ngay_sinh', models.DateField(db_column='NgaySinh')),
                ('sdt', models.CharField(db_column='SDT', max_length=15)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('dia_chi', models.CharField(db_column='DiaChi', max_length=255)),
                ('ngay_tham_gia', models.DateField(db_column='NgayThamGia', default=django.utils.timezone.localdate)),
                ('trang_thai', models.BooleanField(db_column='TrangThai', default=True)),
                ('tai_khoan', models.OneToOneField(db_column='MaTK', on_delete=django.db.models.deletion.PROTECT, related_name='ho_so_hoi_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HoiVien',
                'ordering': ('ma_hv',),
            },
        ),
        migrations.CreateModel(
            name='HuanLuyenVien',
            fields=[
                ('ma_pt', models.CharField(db_column='MaPT', max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(db_column='HoTen', max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], db_column='GioiTinh', max_length=5)),
                ('ngay_sinh', models.DateField(db_column='NgaySinh')),
                ('sdt', models.CharField(db_column='SDT', max_length=15)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('dia_chi', models.CharField(db_column='DiaChi', max_length=255)),
                ('ngay_vao_lam', models.DateField(db_column='NgayVaoLam', default=django.utils.timezone.localdate)),
                ('trang_thai', models.BooleanField(db_column='TrangThai', default=True)),
                ('tai_khoan', models.OneToOneField(db_column='MaTK', on_delete=django.db.models.deletion.PROTECT, related_name='ho_so_huan_luyen_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HuanLuyenVien',
                'ordering': ('ma_pt',),
            },
        ),
        migrations.CreateModel(
            name='LeTan',
            fields=[
                ('ma_lt', models.CharField(db_column='MaLT', max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(db_column='HoTen', max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], db_column='GioiTinh', max_length=5)),
                ('ngay_sinh', models.DateField(db_column='NgaySinh')),
                ('sdt', models.CharField(db_column='SDT', max_length=15)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('dia_chi', models.CharField(db_column='DiaChi', max_length=255)),
                ('ngay_vao_lam', models.DateField(db_column='NgayVaoLam', default=django.utils.timezone.localdate)),
                ('trang_thai', models.BooleanField(db_column='TrangThai', default=True)),
                ('tai_khoan', models.OneToOneField(db_column='MaTK', on_delete=django.db.models.deletion.PROTECT, related_name='ho_so_le_tan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LeTan',
                'ordering': ('ma_lt',),
            },
        ),
    ]
