# Generated by Django 6.0.7 on 2026-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoiTap',
            fields=[
                ('ma_goi', models.CharField(db_column='MaGoi', max_length=10, primary_key=True, serialize=False)),
                ('ten_goi', models.CharField(db_column='TenGoi', max_length=100)),
                ('thoi_han_ngay', models.IntegerField(db_column='ThoiHanNgay')),
                ('gia_tien', models.DecimalField(db_column='GiaTien', decimal_places=2, max_digits=18)),
                ('co_pt', models.BooleanField(db_column='CoPT', default=False)),
                ('so_buoi_pt', models.IntegerField(db_column='SoBuoiPT', default=0)),
                ('mo_ta', models.CharField(blank=True, db_column='MoTa', default='', max_length=255)),
                ('trang_thai', models.BooleanField(db_column='TrangThai', default=True)),
            ],
            options={
                'db_table': 'GoiTap',
                'ordering': ('ma_goi',),
                'constraints': [models.CheckConstraint(condition=models.Q(('thoi_han_ngay__gt', 0)), name='CK_GoiTap_ThoiHanNgay_Positive'), models.CheckConstraint(condition=models.Q(('gia_tien__gte', 0)), name='CK_GoiTap_GiaTien_NonNegative'), models.CheckConstraint(condition=models.Q(models.Q(('co_pt', False), ('so_buoi_pt', 0)), models.Q(('co_pt', True), ('so_buoi_pt__gt', 0)), _connector='OR'), name='CK_GoiTap_CoPT_SoBuoiPT')],
            },
        ),
    ]
