# Generated by Django 6.0.7 on 2026-07-24 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_goitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyGoiTap',
            fields=[
                ('ma_dk', models.CharField(db_column='MaDK', max_length=10, primary_key=True, serialize=False)),
                ('ngay_dang_ky', models.DateField(db_column='NgayDangKy', default=django.utils.timezone.localdate)),
                ('ngay_bat_dau', models.DateField(db_column='NgayBatDau')),
                ('ngay_ket_thuc', models.DateField(db_column='NgayKetThuc', editable=False)),
                ('so_buoi_pt_dang_ky', models.IntegerField(db_column='SoBuoiPTDangKy', default=0, editable=False)),
                ('trang_thai', models.CharField(choices=[('ChuaKichHoat', 'Chưa kích hoạt'), ('HoatDong', 'Hoạt động'), ('HetHan', 'Hết hạn')], db_column='TrangThai', default='ChuaKichHoat', editable=False, max_length=20)),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', default='', max_length=255)),
                ('goi_tap', models.ForeignKey(db_column='MaGoi', on_delete=django.db.models.deletion.PROTECT, related_name='cac_luot_dang_ky', to='gym.goitap')),
                ('hoi_vien', models.ForeignKey(db_column='MaHV', on_delete=django.db.models.deletion.PROTECT, related_name='cac_dang_ky_goi', to='gym.hoivien')),
            ],
            options={
                'db_table': 'DangKyGoiTap',
                'ordering': ('-ngay_dang_ky', 'ma_dk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ngay_ket_thuc__gte', models.F('ngay_bat_dau'))), name='CK_DangKy_NgayKetThuc'), models.CheckConstraint(condition=models.Q(('so_buoi_pt_dang_ky__gte', 0)), name='CK_DangKy_SoBuoiPTDangKy'), models.CheckConstraint(condition=models.Q(('trang_thai__in', ['ChuaKichHoat', 'HoatDong', 'HetHan'])), name='CK_DangKy_TrangThai')],
            },
        ),
    ]
