# Generated by Django 6.0.7 on 2026-07-24 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_dangkygoitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hd', models.CharField(db_column='MaHD', max_length=10, primary_key=True, serialize=False)),
                ('ngay_lap', models.DateTimeField(db_column='NgayLap', default=django.utils.timezone.now)),
                ('tong_tien', models.DecimalField(db_column='TongTien', decimal_places=2, editable=False, max_digits=18)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('TienMat', 'Tiền mặt'), ('ChuyenKhoan', 'Chuyển khoản'), ('The', 'Thẻ')], db_column='PhuongThucThanhToan', max_length=30)),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', default='', max_length=255)),
                ('dang_ky', models.OneToOneField(db_column='MaDK', on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don', to='gym.dangkygoitap')),
                ('le_tan', models.ForeignKey(db_column='MaLT', on_delete=django.db.models.deletion.PROTECT, related_name='cac_hoa_don_da_lap', to='gym.letan')),
            ],
            options={
                'db_table': 'HoaDon',
                'ordering': ('-ngay_lap', 'ma_hd'),
                'constraints': [models.CheckConstraint(condition=models.Q(('tong_tien__gte', 0)), name='CK_HoaDon_TongTien'), models.CheckConstraint(condition=models.Q(('phuong_thuc_thanh_toan__in', ['TienMat', 'ChuyenKhoan', 'The'])), name='CK_HoaDon_PhuongThucThanhToan')],
            },
        ),
    ]
