# Generated by Django 6.0.7 on 2026-07-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_hoadon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichTapPT',
            fields=[
                ('ma_lich', models.CharField(db_column='MaLich', max_length=10, primary_key=True, serialize=False)),
                ('ngay_tap', models.DateField(db_column='NgayTap')),
                ('gio_bat_dau', models.TimeField(db_column='GioBatDau')),
                ('gio_ket_thuc', models.TimeField(db_column='GioKetThuc')),
                ('trang_thai', models.CharField(choices=[('DaLenLich', 'Đã lên lịch'), ('HoanThanh', 'Hoàn thành'), ('Vang', 'Vắng'), ('Huy', 'Hủy')], db_column='TrangThai', default='DaLenLich', max_length=20)),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', default='', max_length=255)),
                ('dang_ky', models.ForeignKey(db_column='MaDK', on_delete=django.db.models.deletion.PROTECT, related_name='cac_lich_tap_pt', to='gym.dangkygoitap')),
                ('huan_luyen_vien', models.ForeignKey(db_column='MaPT', on_delete=django.db.models.deletion.PROTECT, related_name='cac_lich_tap', to='gym.huanluyenvien')),
                ('le_tan', models.ForeignKey(db_column='MaLT', on_delete=django.db.models.deletion.PROTECT, related_name='cac_lich_pt_da_sap_xep', to='gym.letan')),
            ],
            options={
                'db_table': 'LichTapPT',
                'ordering': ('-ngay_tap', '-gio_bat_dau', 'ma_lich'),
                'constraints': [models.CheckConstraint(condition=models.Q(('gio_ket_thuc__gt', models.F('gio_bat_dau'))), name='CK_LichTapPT_GioTap'), models.CheckConstraint(condition=models.Q(('trang_thai__in', ['DaLenLich', 'HoanThanh', 'Vang', 'Huy'])), name='CK_LichTapPT_TrangThai')],
            },
        ),
    ]
