# Generated by Django 6.0.7 on 2026-07-25 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_rename_lichtappt_to_buoitappt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('ma_dd', models.CharField(db_column='MaDD', max_length=10, primary_key=True, serialize=False)),
                ('thoi_gian_diem_danh', models.DateTimeField(db_column='ThoiGianDiemDanh', default=django.utils.timezone.now)),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', default='', max_length=255)),
                ('hoi_vien', models.ForeignKey(db_column='MaHV', on_delete=django.db.models.deletion.PROTECT, related_name='cac_lan_diem_danh', to='gym.hoivien')),
                ('le_tan', models.ForeignKey(db_column='MaLT', on_delete=django.db.models.deletion.PROTECT, related_name='cac_lan_diem_danh_da_ghi_nhan', to='gym.letan')),
            ],
            options={
                'db_table': 'DiemDanh',
                'ordering': ('-thoi_gian_diem_danh', 'ma_dd'),
            },
        ),
    ]
