# Generated by Django 6.0.7 on 2026-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_diemdanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goitap',
            name='ma_goi',
            field=models.CharField(db_column='MaGoi', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
