# Generated by Django 6.0.7 on 2026-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_goitap_ma_goi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoivien',
            name='ma_hv',
            field=models.CharField(db_column='MaHV', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='huanluyenvien',
            name='ma_pt',
            field=models.CharField(db_column='MaPT', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='letan',
            name='ma_lt',
            field=models.CharField(db_column='MaLT', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
