# Generated by Django 6.0.7 on 2026-07-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_hoivien_ma_hv_alter_huanluyenvien_ma_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoitappt',
            name='ma_buoi',
            field=models.CharField(db_column='MaBuoi', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dangkygoitap',
            name='ma_dk',
            field=models.CharField(db_column='MaDK', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diemdanh',
            name='ma_dd',
            field=models.CharField(db_column='MaDD', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ma_hd',
            field=models.CharField(db_column='MaHD', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
