# Generated by Django 6.0.7 on 2026-07-23 13:53

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('ma_tk', models.CharField(db_column='MaTK', max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='TenDangNhap', max_length=50, unique=True)),
                ('password', models.CharField(db_column='MatKhau', max_length=255)),
                ('vai_tro', models.CharField(choices=[('Admin', 'Quản trị viên'), ('LeTan', 'Lễ tân'), ('PT', 'Huấn luyện viên'), ('HoiVien', 'Hội viên')], db_column='VaiTro', max_length=20)),
                ('is_active', models.BooleanField(db_column='TrangThai', default=True)),
                ('date_joined', models.DateTimeField(db_column='NgayTao', default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'TaiKhoan',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
