# Generated by Django 6.0.7 on 2026-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='ma_tk',
            field=models.CharField(db_column='MaTK', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
